### ISSUE TITLE
The subgraph is not indexing the revoked targets transaction

### ISSUE THREAD

**Issue by juliopavila** [gnosis/zodiac-modifier-roles#131]
After hitting this contract method `revokeTarget(),` the subgraph doesn't update the changes

**Comment by jfschwarz** [comment]
This seems to work for me: 

Transaction `revokeTarget(1, 0x7f90122bf0700f9e7e1f688fe926940e8839f353)`:
https://blockscout.com/xdai/mainnet/tx/0xbc9b801063095577d4b47bbc3c0e626466a2707c943c29c95233c276919af4d3

Subgraph [logs](https://thegraph.com/hosted-service/subgraph/jfschwarz/zodiac-roles-gnosis-chain?selected=logs):
```
Done processing trigger, gas_used: 67729915, data_source: Permissions, handler: handleRevokeTarget, total_ms: 4, transaction: 0xbc9b…f4d3, address: 0x0df1…bec6, signature: RevokeTarget(uint16,address)
```

Subgraph [query](https://api.thegraph.com/subgraphs/name/jfschwarz/zodiac-roles-gnosis-chain/graphql?query=%7B%0A++rolesModifier%28id%3A+%220x0df1f08f765238dc0b8beaaddd6681f62e54bec6%22%29+%7B%0A++++id%0A++++roles+%7B%0A++++++members+%7B%0A++++++++member+%7Baddress%7D%0A++++++%7D%0A++++++targets+%7B%0A++++++++address%0A++++++++clearance%0A++++++++functions+%7B%0A++++++++++sighash%0A++++++++++parameters+%7B%0A++++++++++++index%0A++++++++++++comparison%0A++++++++++++comparisonValue%0A++++++++++%7D%0A++++++++%7D%0A++++++%7D%0A++++%7D%0A++%7D%0A%7D):
```JS
{
  "address": "0x7f90122bf0700f9e7e1f688fe926940e8839f353",
  "clearance": "None", // was "Target" before
  "functions": []
}
```
