### ISSUE TITLE
Roles App does not parse Roles mod address when used as Safe App

### ISSUE THREAD

**Issue by samepant** [gnosis/zodiac-modifier-roles#137]
**Describe the bug**
When the "Open Roles Mod" button is clicked in the Zodiac Safe App, the Roles App opens, but the mod is not recognized from the url.

**To Reproduce**
1. Go to Safe App with active Roles Mod
2. Click on "Open Roles Mod" link
3. Roles App opens without connecting to mod

**Expected behavior**
Roles App should auto connect to Roles mod address when it's in the URL

**Screenshots / logs**
![Screen Shot 2022-08-11 at 11 55 23 AM](https://user-images.githubusercontent.com/6718506/184177576-5fdea639-a4a0-48bf-b66d-ae7ce5755869.png)

**Comment by manboy-eth** [comment]
Fixed in https://github.com/gnosis/zodiac-safe-app/pull/127
