### ISSUE TITLE
bundle multisend on setup

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/zodiac-modifier-roles#151]
**Is your feature request related to a problem? Please describe.**
When we setup a roles mod, we should prompt the user to choose which multisend contract they want to use.
Currently, we don't set it for users which means that the pilot extension won't work by default.

**Describe the solution you'd like**
We should default to `0x40A2aCCbd92BCA938b02010E17A5b8929b49130D`, but give the user the option to input a different address or choose not to set a multisend address (in which case we don't bundle a `setMultisend()` call).

**Comment by cristovaoth** [comment]
@auryn-macmillan just realized something. As we can't simply bundle the setMultisend into the create stack - the target would be the actual roles module, which is at that point not yet deployed, and hence has address undetermined 🤕

**Comment by auryn-macmillan** [comment]
Created this in the wrong repo.
Re-created over here: https://github.com/gnosis/zodiac-safe-app/issues/160
