### ISSUE TITLE
Subgraph has entries for unscoped parameters

### ISSUE THREAD

**Issue by jfschwarz** [gnosis/zodiac-modifier-roles#185]
Look at this query's result:

https://api.thegraph.com/subgraphs/name/samepant/zodiac-roles-mod-mainnet/graphql?query=%7B%0A++function%28%0A++++id%3A+%220xef14e0f66a2e22bbe85bfa53b3f956354ce51e62-ROLE-3.0-TARGET-0xba12222222228d8ba445958a75a0704d566bf2c8-FUNCTION-0x52bbbe29%22%0A++%29+%7B%0A++++id%0A++++sighash%0A++++parameters+%7B%0A++++++index%0A++++++type%0A++++++comparison%0A++++++comparisonValue%0A++++%7D%0A++%7D%0A%7D

The parameters at indices 4 and 5 are actually unscoped, but the subgraph returns the following entries:

```
        {
          "index": 4,
          "type": "Static",
          "comparison": "EqualTo",
          "comparisonValue": [
            "0x"
          ]
        },
        {
          "index": 5,
          "type": "Static",
          "comparison": "EqualTo",
          "comparisonValue": [
            "0x"
          ]
        },
```

It is expected that the entries are NOT present in the array.

**Comment by manboy-eth** [comment]
Aha, I think this is only present on outdated subgraphs.

It should have been fixed by https://github.com/gnosis/zodiac-modifier-roles/pull/180.
