### ISSUE TITLE
Update the event emitted in Roles.assignRoles to indicate if membership is assigned or revoked

### ISSUE THREAD

**Issue by asgeir-eth** [gnosis/zodiac-modifier-roles#30]
Since the assignRoles function is used both for assigning and revoking roles it could make sense to add the memberOf (calldata array) to the AssignRoles event in order to easily see if a role was given or revoked.

Perhaps it then will also make sense to rename the event from AssignRoles to something like UpdateRoles.

Something like this:
```emit UpdateRoles(module, _roles, memberOf)```

**Comment by cristovaoth** [comment]
Fixed in the "audit-feedback" branch

Note that this branch also has functions that touch scope emitting the resulting scopeConfig. This important, and might save some work off chain (no need to reduce through all scoping events in order to calculate a function's current configuration)

**Comment by asgeir-eth** [comment]
Excellent, thank you, @cristovaoth.
