### ISSUE TITLE
Notify user of losing changes to role before navigating away.

### ISSUE THREAD

**Issue by cedricwaxwing** [gnosis/zodiac-modifier-roles#69]
"Your changes will be lost" modal should show when clicking "View Roles" from RoleView with changes.

**Comment by carlosfebres** [comment]
I was thinking about this, great minds think alike 😉 hahaha

**Comment by cedricwaxwing** [comment]
Excellent. :) I'll create a UI for this and assign you when it's ready @carlosfebres

**Comment by cedricwaxwing** [comment]
https://www.figma.com/file/h2nRHyTfrJb2hhXME6FDX4/Zodiac-Roles-Modifier?node-id=344%3A12582
