### ISSUE TITLE
Revert when internal transaction fails

### ISSUE THREAD

**Issue by jfschwarz** [gnosis/zodiac-modifier-roles#7]
In our Zodiac Pilot tests we're calling the `execTransactionFromModule` of the Safe contract from another Safe that is enabled as a module. We're seeing transactions failing sporadically with out of gas exceptions.

I believe that is, because `execTransactionFromModule` does not fail if the internal transaction fails. So the minimum amount of gas to make the overall transaction succeed does not cover the internal transaction. Gas estimation will therefore return an amount that is too low. Here's one instance of this happening: https://rinkeby.etherscan.io/tx/0xefe094bcccaf318f29d3cf52953bc17252fa7ffc3cbcfed2461749ce635c8635#internal

Looking at how this module currently implements `execTransactionFromModule` I think we'll be susceptible to the same problem. I would therefore propose to revert if the return value of the `exec` call ([L310](https://github.com/gnosis/zodiac-modifier-roles/blob/main/contracts/Roles.sol#L310)) is false.

This might break composability a bit, since upstream modules won't be able to decide for themselves whether the tx should revert or not. So we could also consider adding an extra function that is reverting and that we can then use for Zodiac Pilot.

**Comment by auryn-macmillan** [comment]
Yeah, I just experienced this issue while testing out the pilot with Uniswap on Rinkeby.

**Comment by cristovaoth** [comment]
@auryn-macmillan I saw this working on Uniswap Rinkeby up until November 30th. Any clue why it stopped working?

**Comment by auryn-macmillan** [comment]
I honestly have no idea.

**Comment by jfschwarz** [comment]
I asked Richard. He's surprised it ever worked but confirmed that they have implemented some changes in the Safe that influences gas estimation.

If we want to keep the module function non-reverting, we'll have to provide the gas amount from the client. The Safe WalletConnect app does not seem to allow that currently, though. So we'd have to check on that with the Safe team.
