### ISSUE TITLE
Write "What is a member" section

### ISSUE THREAD

**Issue by cedricwaxwing** [gnosis/zodiac-modifier-roles#70]

**Comment by cedricwaxwing** [comment]
@asgeir-eth I think it would be helpful to also mention where one might find a member address if they're using the Zodiac app. What do you think? Something like:

"If you're using the Zodiac App, you can copy the member's address from the appropriate module in the left sidebar."

**Comment by asgeir-eth** [comment]
> @asgeir-eth I think it would be helpful to also mention where one might find a member address if they're using the Zodiac app. What do you think? Something like:
> 
> "If you're using the Zodiac App, you can copy the member's address from the appropriate module in the left sidebar."

Updated :)

**Comment by asgeir-eth** [comment]
> @asgeir-eth I think it would be helpful to also mention where one might find a member address if they're using the Zodiac app. What do you think? Something like:
> 
> "If you're using the Zodiac App, you can copy the member's address from the appropriate module in the left sidebar."

After digging more into the contracts I realize that the list of enabled modifiers and modules in the Zodiac app is not the set of members for a role.
There is a separate set of modules in the Roles Modifier itself where members must be added.

I added an issue (#89) for adding a member to the set of enabled modules within the Roles Modifier when adding a member.
