### ISSUE TITLE
Write "What is a target" section

### ISSUE THREAD

**Issue by cedricwaxwing** [gnosis/zodiac-modifier-roles#71]

**Comment by cedricwaxwing** [comment]
Similarly to #70, I think it's helpful if we add where the target address can be found if the user is using the Zodiac app.

"The target address can be found in the right panel of the appropriate module. See `target` in the `Read Contract` tab."

**Comment by asgeir-eth** [comment]
> Similarly to #70, I think it's helpful if we add where the target address can be found if the user is using the Zodiac app.
> 
> "The target address can be found in the right panel of the appropriate module. See `target` in the `Read Contract` tab."

But the target can be any address on the network (ethereum). The target mentioned in `target` in the `Read Contract` tab" is something else unrelated to what a target is in the context of a role in the roles modifier.
