### ISSUE TITLE
Publish tutorial on live gnosis.github.io docs

### ISSUE THREAD

**Issue by cedricwaxwing** [gnosis/zodiac-modifier-roles#73]

**Comment by auryn-macmillan** [comment]
You can make edits to https://gnosis.github.io/zodiac/ by making PRs to https://github.com/gnosis/zodiac/tree/documentation. Anything that's merged into that branch will be deployed automatically.

**Comment by auryn-macmillan** [comment]
Sorry for the slow reply, btw.

**Comment by cedricwaxwing** [comment]
I don't know how I missed the docs repo there 😅 thank you.
