### ISSUE TITLE
Create Target's functions list 

### ISSUE THREAD

**Issue by carlosfebres** [gnosis/zodiac-modifier-roles#77]
Create this section:

<img width="740" alt="image" src="https://user-images.githubusercontent.com/2939980/153579013-0d4c4ec2-4c4b-4ce3-92fc-1ddd2c1fec54.png">

**Comment by cedricwaxwing** [comment]
Allow all functions should be in the indeterminate state when only some of the functions are selected:
![image](https://user-images.githubusercontent.com/80348806/154350198-810c8246-0702-401f-ab6d-27692f0d34ca.png)
