### ISSUE TITLE
Handle duplicate members/targets

### ISSUE THREAD

**Issue by cedricwaxwing** [gnosis/zodiac-modifier-roles#79]
If you add a duplicate target address, it currently applies the "recently added" style to the UI.

I'm not sure if we should run a validation when adding members/targets to see if that address already exists, but if it's ok to have duplicates, then we need to make sure that the "recently added" style is only applying to the new address.

**Comment by carlosfebres** [comment]
Digging into the contract, we can't have duplicated targets in a role, the last one would overwrite the first one.

@asgeir-eth could you confirm this please?

**Comment by asgeir-eth** [comment]
> Digging into the contract, we can't have duplicated targets in a role, the last one would overwrite the first one.
> 
> @asgeir-eth could you confirm this please?

Yes, that is true. The target address is used as a key in the role's target mapping. So a new call to `allowTarget` or `scopeTarget` will just overwrite the old target.

**Comment by cedricwaxwing** [comment]
Ok makes sense. Thanks guys. I’ll think through an appropriate flow here and keep you posted.

**Comment by cedricwaxwing** [comment]
Something simple like this should do the trick:
![image](https://user-images.githubusercontent.com/80348806/154299705-5d79a20d-c6bf-40c7-a5a2-52058bc40649.png)


[Figma](https://www.figma.com/file/h2nRHyTfrJb2hhXME6FDX4/Zodiac-Roles-Modifier?node-id=388%3A17283)

@carlosfebres I'm not loving the way the error text shows up on the gray modal background. Do you know if there's an example of the error code on the exit map on a modal like this?
